disabled_rules: # Regras que você não quer aplicar
  - trailing_whitespace
  - todo
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name
  - nesting
  - type_name

opt_in_rules: # Regras que não estão ativadas por padrão
  - empty_count
  - missing_docs
  - closure_end_indentation
  - closure_spacing
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline

# Algumas regras de configuração
line_length: 210
cyclomatic_complexity:
  ignores_case_statements: true
excluded:
  - .build/