disabled_rules:
  - colon
  - comma
  - control_statement
opt_in_rules:
  - empty_count

# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

analyzer_rules:
  - explicit_self

included:
  - Sources/
  - Tests/
excluded:
  - .build/

allow_zero_lintable_files: false

force_cast: warning
force_try:
  severity: warning
line_length: 120
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"