name: Run Makefile into PSUICore

on:
  push:
    branches: [ main ]
    paths:
      - 'PSUICore/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'PSUICore/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install make

    - name: Run Make
      run: |
        cd PSUICore && make all
